### PR TITLE
WIP: enable explicit use of seeds in ffi and Python

### PR DESCRIPTION
**Pull request by dkg**
I think these changes should enable the use of key generation with seeds using the FFI and Python.

These should be deterministic functions, so if there are any test vectors that you think we should run them against, i'd be happy to test them out.

I'm also fine with considering other API approaches on both the FFI and Python (e.g. in Python, i can imagine wanting to just get the seed, enc, and dec in a single function call for simplicity), but i wanted to propose a set of changes that tracks fairly closely for now.

### CODE REVIEW

**Comment by dkg** [comment]
OK, i think this is ready to go now.  i've updated the ffi test to make sure that keygen_from_seed is deterministic, and i've added a simple python script to test the fips203 module's generation from seed against the NIST keygen vectors.

**Comment by dkg** [comment]
If these changes seem reasonable to you, i'd like to aim for publication of fips203-ffi 0.4.0 on https://crates.io/crates/fips203-ffi    Once that's done, i should be able to handle the updates to https://pypi.org/project/fips203/

**Comment by integritychain** [comment]
Thank you @dkg !! I expect to make a quick pass over the code during the next few days. I am then happy to publish new versions with everything aligned.

**Comment by integritychain** [comment]
v0.4.1 published just now (both crates). Thanks for your help on this!

**Comment by dkg** [comment]
I published 0.4.1 to https://pypi.org/project/fips203/ just now.  It's also been uploaded to debian unstable.

**Comment by integritychain** [comment]
Thank you!!

**Pull request merged**
